# .github/release-drafter.yml
name-template: "Next Release"
tag-template: ""
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
change-template: "- $TITLE" # Removed @$AUTHOR to hide authors
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## What's Changed

  $CHANGES
exclude-labels:
  - "skip-changelog"
  - "released"
autolabeler:
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
